version: '3'
services:
  main_server:
    container_name: "main-server"
    restart: always
    build: ./main-server/
    ports:
    - "3000:3000"
  board:
    container_name: "board"
    restart: always
    build: ./board/
    ports:
    - "5000:5000"